package com.akinsete.ourgrocerylist.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GROCERY".
 */
@Entity
public class Grocery {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;
    private int quantity;
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Grocery() {
    }

    public Grocery(Long id) {
        this.id = id;
    }

    @Generated
    public Grocery(Long id, String name, int quantity, String status) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END


    @Override
    public String toString() {
        return quantity + " " +name;
    }
}
